language: ruby
bundler_args: --without development
before_install:
  - gem install bundler
  - rvm get head
  - rvm use jruby-9.0.5.0 --install
rvm:
  - 2.3.0
  - 2.2.4
  - 2.1.8
  - jruby-9.0.5.0
  - rbx-2.11
